
trigger:
  - master

pool:
  vmImage: 'ubuntu-18.04'

variables:
  phpVersion: 7.2

steps:
- script: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Use PHP version $(phpVersion)'

- script: composer install --no-interaction --prefer-dist
  displayName: 'composer install'
    
- task: SonarQubePrepare@5
  inputs:
    SonarQube: 'scngrok'
    scannerMode: 'CLI'
    configMode: 'file'
    extraProperties: |
      sonar.projectKey=alexandreholzhey_subject-php
      sonar.organization=alexandreholzheyazdo

- task: SonarQubeAnalyze@5